//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyRadioLink.Server.Properties {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyRadioLink.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ban.
        /// </summary>
        public static string BtnBan {
            get {
                return ResourceManager.GetString("BtnBan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clients....
        /// </summary>
        public static string BtnClientAdmin {
            get {
                return ResourceManager.GetString("BtnClientAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        public static string BtnKick {
            get {
                return ResourceManager.GetString("BtnKick", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string BtnMute {
            get {
                return ResourceManager.GetString("BtnMute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Server.
        /// </summary>
        public static string BtnStartServer {
            get {
                return ResourceManager.GetString("BtnStartServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop Server.
        /// </summary>
        public static string BtnStopServer {
            get {
                return ResourceManager.GetString("BtnStopServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string GroupAccess {
            get {
                return ResourceManager.GetString("GroupAccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client features.
        /// </summary>
        public static string GroupClientFeatures {
            get {
                return ResourceManager.GetString("GroupClientFeatures", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Frequencies.
        /// </summary>
        public static string GroupFrequencies {
            get {
                return ResourceManager.GetString("GroupFrequencies", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logging and export.
        /// </summary>
        public static string GroupLogging {
            get {
                return ResourceManager.GetString("GroupLogging", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Radio realism.
        /// </summary>
        public static string GroupRadioRealism {
            get {
                return ResourceManager.GetString("GroupRadioRealism", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keep transmission logs (days).
        /// </summary>
        public static string LabelArchiveTime {
            get {
                return ResourceManager.GetString("LabelArchiveTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clean frequencies (no radio effects, MHz).
        /// </summary>
        public static string LabelCleanFreq {
            get {
                return ResourceManager.GetString("LabelCleanFreq", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clients:.
        /// </summary>
        public static string LabelClients {
            get {
                return ResourceManager.GetString("LabelClients", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings file:.
        /// </summary>
        public static string LabelConfigFile {
            get {
                return ResourceManager.GetString("LabelConfigFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export client list (clients-list.json).
        /// </summary>
        public static string LabelExportList {
            get {
                return ResourceManager.GetString("LabelExportList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Radio interference (simultaneous transmissions).
        /// </summary>
        public static string LabelRealRx {
            get {
                return ResourceManager.GetString("LabelRealRx", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Half-duplex radios (can't receive while transmitting).
        /// </summary>
        public static string LabelRealTx {
            get {
                return ResourceManager.GetString("LabelRealTx", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server password.
        /// </summary>
        public static string LabelServerPassword {
            get {
                return ResourceManager.GetString("LabelServerPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show transmitter name.
        /// </summary>
        public static string LabelShowTransmitterName {
            get {
                return ResourceManager.GetString("LabelShowTransmitterName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Radio check (echo) frequencies (MHz).
        /// </summary>
        public static string LabelTestFreq {
            get {
                return ResourceManager.GetString("LabelTestFreq", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Log transmissions (CSV).
        /// </summary>
        public static string LabelTransmissionLog {
            get {
                return ResourceManager.GetString("LabelTransmissionLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show number of users on a frequency.
        /// </summary>
        public static string LabelTunedCount {
            get {
                return ResourceManager.GetString("LabelTunedCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to ban {0}?.
        /// </summary>
        public static string MsgBoxBan {
            get {
                return ResourceManager.GetString("MsgBoxBan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ban Confirmation.
        /// </summary>
        public static string MsgBoxBanTitle {
            get {
                return ResourceManager.GetString("MsgBoxBanTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to kick {0}?.
        /// </summary>
        public static string MsgBoxKick {
            get {
                return ResourceManager.GetString("MsgBoxKick", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Kick Confirmation.
        /// </summary>
        public static string MsgBoxKickTitle {
            get {
                return ResourceManager.GetString("MsgBoxKickTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The server could not be started. {0} Close the other server, or change SERVER_PORT / SERVER_IP in {1} and click "Start Server"..
        /// </summary>
        public static string MsgBoxStartFailed {
            get {
                return ResourceManager.GetString("MsgBoxStartFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server running.
        /// </summary>
        public static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Server stopped.
        /// </summary>
        public static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connected Clients.
        /// </summary>
        public static string TitleClientList {
            get {
                return ResourceManager.GetString("TitleClientList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EasyRadioLink Server.
        /// </summary>
        public static string TitleServer {
            get {
                return ResourceManager.GetString("TitleServer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to How many days of transmission logs are kept (0-7)..
        /// </summary>
        public static string TooltipArchiveTime {
            get {
                return ResourceManager.GetString("TooltipArchiveTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transmissions on these frequencies are played without radio effects (static, filters, clicks). Comma separated, use a dot as decimal separator, e.g. 145.5,446.1.
        /// </summary>
        public static string TooltipCleanFreq {
            get {
                return ResourceManager.GetString("TooltipCleanFreq", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Writes the connected clients to clients-list.json next to server.cfg every 5 seconds (path: CLIENT_EXPORT_FILE_PATH in server.cfg)..
        /// </summary>
        public static string TooltipExportList {
            get {
                return ResourceManager.GetString("TooltipExportList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Two stations transmitting at the same time on one frequency interfere with each other..
        /// </summary>
        public static string TooltipRealRx {
            get {
                return ResourceManager.GetString("TooltipRealRx", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A radio cannot receive while it is transmitting..
        /// </summary>
        public static string TooltipRealTx {
            get {
                return ResourceManager.GetString("TooltipRealTx", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clients must enter this password to connect. Leave empty for an open server. The password is sent unencrypted..
        /// </summary>
        public static string TooltipServerPassword {
            get {
                return ResourceManager.GetString("TooltipServerPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clients see the name of the user who is transmitting..
        /// </summary>
        public static string TooltipShowTransmitterName {
            get {
                return ResourceManager.GetString("TooltipShowTransmitterName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transmissions on these frequencies are played back to the sender (radio check). Comma separated, use a dot as decimal separator, e.g. 27.405,446.19375.
        /// </summary>
        public static string TooltipTestFreq {
            get {
                return ResourceManager.GetString("TooltipTestFreq", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Writes one CSV line per transmission to a daily &lt;date&gt;-transmissionlog.csv file next to server.cfg..
        /// </summary>
        public static string TooltipTransmissionLog {
            get {
                return ResourceManager.GetString("TooltipTransmissionLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clients see how many other users are tuned to their frequency..
        /// </summary>
        public static string TooltipTunedCount {
            get {
                return ResourceManager.GetString("TooltipTunedCount", resourceCulture);
            }
        }
    }
}
