//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyRadioLink.Installer.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyRadioLink.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create a desktop shortcut.
        /// </summary>
        internal static string CreateDesktopShortcut {
            get {
                return ResourceManager.GetString("CreateDesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Start menu shortcuts.
        /// </summary>
        internal static string CreateStartMenuShortcut {
            get {
                return ResourceManager.GetString("CreateStartMenuShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your settings (%AppData%\EasyRadioLink) and recordings (Documents\EasyRadioLink\Recordings) are kept when you update or uninstall..
        /// </summary>
        internal static string DataNote {
            get {
                return ResourceManager.GetString("DataNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install / Update.
        /// </summary>
        internal static string InstallButton {
            get {
                return ResourceManager.GetString("InstallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        internal static string InstallingButton {
            get {
                return ResourceManager.GetString("InstallingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyRadioLink Setup.
        /// </summary>
        internal static string intro {
            get {
                return ResourceManager.GetString("intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs the EasyRadioLink client, the server and the command-line server..
        /// </summary>
        internal static string IntroDescription {
            get {
                return ResourceManager.GetString("IntroDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close EasyRadioLink.
        /// </summary>
        internal static string MsgBoxCloseApps {
            get {
                return ResourceManager.GetString("MsgBoxCloseApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following EasyRadioLink programs are running and will be closed: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxCloseAppsText {
            get {
                return ResourceManager.GetString("MsgBoxCloseAppsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please extract the download first.
        /// </summary>
        internal static string MsgBoxExtracted {
            get {
                return ResourceManager.GetString("MsgBoxExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some installation files are missing. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxExtractedText {
            get {
                return ResourceManager.GetString("MsgBoxExtractedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid install location.
        /// </summary>
        internal static string MsgBoxFolder {
            get {
                return ResourceManager.GetString("MsgBoxFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder
        ///{0}
        ///already contains files of another program. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxFolderNotEmptyText {
            get {
                return ResourceManager.GetString("MsgBoxFolderNotEmptyText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please choose a different install folder. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxFolderText {
            get {
                return ResourceManager.GetString("MsgBoxFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation error.
        /// </summary>
        internal static string MsgBoxInstallError {
            get {
                return ResourceManager.GetString("MsgBoxInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installation failed. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxInstallErrorText {
            get {
                return ResourceManager.GetString("MsgBoxInstallErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyRadioLink {0} was installed successfully to: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxInstallSuccessText {
            get {
                return ResourceManager.GetString("MsgBoxInstallSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyRadioLink Setup.
        /// </summary>
        internal static string MsgBoxInstallTitle {
            get {
                return ResourceManager.GetString("MsgBoxInstallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... and {0} more.
        /// </summary>
        internal static string MsgBoxMoreFiles {
            get {
                return ResourceManager.GetString("MsgBoxMoreFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyRadioLink was not found in: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxNotInstalledText {
            get {
                return ResourceManager.GetString("MsgBoxNotInstalledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart Windows to finish the installation of the Microsoft Visual C++ Runtime..
        /// </summary>
        internal static string MsgBoxRebootText {
            get {
                return ResourceManager.GetString("MsgBoxRebootText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyRadioLink was uninstalled. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxRemovedKeptText {
            get {
                return ResourceManager.GetString("MsgBoxRemovedKeptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyRadioLink could not be uninstalled completely: {0} program files in
        ///{1}
        ///are in use by another program. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxRemovedLockedText {
            get {
                return ResourceManager.GetString("MsgBoxRemovedLockedText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EasyRadioLink was uninstalled successfully..
        /// </summary>
        internal static string MsgBoxRemovedText {
            get {
                return ResourceManager.GetString("MsgBoxRemovedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyRadioLink uninstalled.
        /// </summary>
        internal static string MsgBoxRemovedText2 {
            get {
                return ResourceManager.GetString("MsgBoxRemovedText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyRadioLink is registered as installed in: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxRemoveEntryText {
            get {
                return ResourceManager.GetString("MsgBoxRemoveEntryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setup was started from the installation folder. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxRunningFromInstallText {
            get {
                return ResourceManager.GetString("MsgBoxRunningFromInstallText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shortcuts could not be created. You can start EasyRadioLink with Client\EasyRadioLink.exe in the install folder..
        /// </summary>
        internal static string MsgBoxShortcutsWarningText {
            get {
                return ResourceManager.GetString("MsgBoxShortcutsWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to uninstall EasyRadioLink from: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxUninstallConfirm {
            get {
                return ResourceManager.GetString("MsgBoxUninstallConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The install folder contains files that were not installed by the setup, for example server settings (server.cfg), presets or log files: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxUninstallDataText {
            get {
                return ResourceManager.GetString("MsgBoxUninstallDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall error.
        /// </summary>
        internal static string MsgBoxUninstallError {
            get {
                return ResourceManager.GetString("MsgBoxUninstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uninstall failed. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MsgBoxUninstallErrorText {
            get {
                return ResourceManager.GetString("MsgBoxUninstallErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling EasyRadioLink....
        /// </summary>
        internal static string MsgBoxUninstalling {
            get {
                return ResourceManager.GetString("MsgBoxUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Microsoft Visual C++ Redistributable (x64) could not be installed (exit code {0}). EasyRadioLink needs it for audio. Please install the latest Microsoft Visual C++ Redistributable (x64) from microsoft.com..
        /// </summary>
        internal static string MsgBoxVcRedistWarningText {
            get {
                return ResourceManager.GetString("MsgBoxVcRedistWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing running EasyRadioLink programs....
        /// </summary>
        internal static string ProgressClosingApps {
            get {
                return ResourceManager.GetString("ProgressClosingApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying program files....
        /// </summary>
        internal static string ProgressCopying {
            get {
                return ResourceManager.GetString("ProgressCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string ProgressDone {
            get {
                return ResourceManager.GetString("ProgressDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the list of installed apps....
        /// </summary>
        internal static string ProgressRegistry {
            get {
                return ResourceManager.GetString("ProgressRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing program files....
        /// </summary>
        internal static string ProgressRemoving {
            get {
                return ResourceManager.GetString("ProgressRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing the previous version....
        /// </summary>
        internal static string ProgressRemovingOld {
            get {
                return ResourceManager.GetString("ProgressRemovingOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating shortcuts....
        /// </summary>
        internal static string ProgressShortcuts {
            get {
                return ResourceManager.GetString("ProgressShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing the Microsoft Visual C++ Runtime....
        /// </summary>
        internal static string ProgressVcRedist {
            get {
                return ResourceManager.GetString("ProgressVcRedist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling....
        /// </summary>
        internal static string RemovingButton {
            get {
                return ResourceManager.GetString("RemovingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string srPathButton {
            get {
                return ResourceManager.GetString("srPathButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Choose the install location.
        /// </summary>
        internal static string step2 {
            get {
                return ResourceManager.GetString("step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Install or uninstall.
        /// </summary>
        internal static string step4 {
            get {
                return ResourceManager.GetString("step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyRadioLink Setup.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
